---
title: "Stationary"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

A stationary time series is one whose properties do not depend on the time at which the series is observed. 14. Thus, time series with trends, or with seasonality, are not stationary — the trend and seasonality will affect the value of the time series at different times.

# Strictly Stationary

Joint Distribution of ...

## Implications

- Identically distributed but might not be independent
- Joint distribution of two RV's depends only on the lag space, not where you are.

Autocovariance dependence only depends on separation. It's not constant but depends on the lag.

ACF: $$\gamma(t1,t2) = \gamma(t2 - t1) = \gamma(\tau)$$

# Weak Stationary

Mean function gives constant average:

$$\mu(t) = \mu$$
ACF just depends upon lag spacing:

$$\gamma(t1,t2) = \gamma(t2 - t1) = \gamma(\tau)$$
Let lag = 0, and it's a constant variance function as well.

Implication: Constant Variance

# Examples

- White Noise - trivially stationary
- Random Walks - **Not** stationary
- Moving averages - Are stationary processes

## White Noise

Stationary
Mean function

$$u(t) = 0$$
$$X_t \sim iid(0,\sigma^2)$$
$$X_t \sim \mathcal{N}(0,\sigma^2)$$

## Random Walks 

- **Not** stationary

$$Z_i \sim iid(\mu, \sigma^2)$$

$\mu$ could be zero, but still not stationary.

A journey is  just the sum of all its individual steps

Expected value and variance increase linearly with time.

The variance is not constant, so your process is not stationary.


## Moving averages

- Are stationary processes

MA(q) a linear combination of the underlying Z's:
$$X_t = \beta_0 Z_t + \beta_1 Z_{t-1} + \cdots + \beta_q Z_{t-q}$$

Betas are weightings.

Noise at t + Noise at t-1 + ... Noise at t-q

MA(q) - q!!!

Hard to come up with a naturally occuring moving average.

## 

# References

- https://www.youtube.com/watch?v=JytDF8ph2ko
